name: simnibs_env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pyopengl
  - pytest
  - cython
  - mock
  - requests
  - pip
  - cgal=5.5.1
  - libwebp
  - pillow
  - numpy < 2
  - scipy
  - h5py
  - nibabel
  - jsonschema
  - numba
  - pyqt
  - packaging
  - zlib
  - matplotlib
  - python-mumps
  - pip:
    - simnibs/external/wheels/fmm3dpy-1.0.0-cp311-cp311-macosx_11_0_arm64.whl
    - charm_gems==1.3.3
    - pygpc==0.3.9
