name: simnibs_env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pyopengl
  - pytest
  - cython
  - mock
  - requests
  - freeglut
  - pip
  - cgal=5.5.1
  - libwebp
  - pillow
  - numpy
  - scipy
  - h5py
  - nibabel
  - jsonschema
  - tbb-devel
  - numba
  - pyqt
  - mkl
  - packaging
  - zlib
  - pip:
    - simnibs/external/bin/osx/fmm3dpy-1.0.0-cp39-cp39-macosx_10_9_x86_64.whl #because M1 does not like AVX
    - charm_gems==1.3.3
    - pygpc==0.3.9
