name: simnibs_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pyopengl
  - pytest
  - cython
  - mock
  - requests
  - freeglut
  - pip
  - cgal-cpp=5.4
  - libwebp
  - pillow
  - scipy
  - h5py
  - nibabel
  - jsonschema
  - tbb-devel
  - numba
  - matplotlib
  - seaborn
  - pyqt
  - mkl
  - packaging
  - PySide2
  - pip:
    - fmm3dpy==1.0.0
    - charm_gems==1.3.3
    - pygpc==0.3.8
