name: simnibs_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - scipy
  - h5py
  - pyopengl
  - pytest
  - cython
  - mock
  - packaging
  - requests
  - freeglut
  - pip
  - matplotlib
  - boost=1.78.0
  - tbb=2021.6.0
  - libwebp
  - pillow
  - nibabel
  - pyqt
  - mkl
  - jsonschema
  - numba
  - seaborn
  - pip:
    - fmm3dpy==1.0.0
    - charm_gems==1.3.3
    - pygpc==0.3.8
