name: simnibs_env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pyopengl
  - pytest
  - cython
  - mock
  - requests
  - pip
  - cgal=5.5.1
  - libwebp
  - pillow
  - numpy < 2
  - scipy
  - h5py
  - nibabel
  - jsonschema
  - numba
  - pyqt
  - zlib
  - matplotlib
  - python-mumps
  - setuptools-scm
  - pip:
    - simnibs/external/wheels/fmm3dpy-1.0.0-cp311-cp311-macosx_11_0_arm64.whl
    - samseg==0.4a0
    - pygpc==0.3.9
    - https://github.com/jduemose/simple-petsc4py/releases/download/v3.21.5/petsc4py-3.21.5-cp311-cp311-macosx_14_0_arm64.whl
