name: simnibs_env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy < 2
  - pyopengl
  - pytest
  - cython
  - mock
  - requests
  - freeglut
  - pip
  - cgal-cpp=5.5.1
  - libwebp
  - pillow
  - scipy
  - h5py
  - nibabel
  - jsonschema
  - tbb-devel
  - numba
  - pyqt
  - mkl
  - packaging
  - zlib
  - matplotlib
  - python-mumps
  - pip:
    - fmm3dpy==1.0.0
    - charm_gems==1.3.3
    - pygpc==0.3.9
