name: simnibs_env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy < 2
  - pyopengl
  - pytest
  - cython
  - mock
  - requests
  - freeglut
  - pip
  - cgal-cpp=5.5.1
  - libwebp
  - pillow
  - scipy
  - h5py
  - nibabel
  - jsonschema
  - tbb-devel
  - numba
  - pyqt
  - mkl
  - packaging
  - zlib
  - matplotlib
  - python-mumps
  - setuptools-scm
  - pip:
    - fmm3dpy==1.0.0
    - https://github.com/oulap/samseg_wheels/releases/download/dev/samseg-0+untagged.1.g136b181-cp311-cp311-manylinux_2_28_x86_64.whl
    - pygpc==0.3.9
    - https://github.com/jduemose/simple-petsc4py/releases/download/v3.21.5/petsc4py-3.21.5-cp311-cp311-manylinux_2_28_x86_64.whl
